language: node_js
node_js: lts/*
cache:
  yarn: true
  directories:
  - node_modules
env:
  global:
  - secure: M4ozZXUxAAY8Aj4f3t4a9rZTeEqng1wNuJ/x3f9QqvS0Hs28SWyj0EETgkW3ihFBzk/QRe8MbrEB48RmIFUyiTFHO2GfT/VDwToIUt2BNuAGiW6T6XGFfLrpZt8U3E5xERXP6MsTP7t6/CWzFkfgFFad5+fs3tO5b1db4Bea7iQy3rBMroi7KBc08pmuQc8PdFk7nYOicbI/XR7hpsbSPEq6ecVpIg+/BA7IBkOnPy329zdnxJsDLbY0b2KbMNaqNJ1daIEM3LguVuIyzvdMj4ZimC+oR1grEIxR9VyORKKF6u/LNs5ZGVRfEK6mJey1x0G+12igxAhR+w3lWCGg6XvhoTg10cQtd1p9UfL6A7JPtI9sQ88+Z3w9gk8uxShjnrjXOLpGXIlbUiL6xH6CbMis5xj5IXtt6+va4tcIbO2z9Sdj1yGB5FkYhDP9VaPUTQqDyI4SkRVKQln02h2BRoipDjLmPwrsfj0trIoMboFEJIzc88BheZQOTzQeurV1EVON8g2cstDeCPfcMzR9zBEXjq+vZaWJNjiEmK03x6wQxwnHucdX7VC1zndgsbG0TBpJGDKvAXm8X416YWKMgEWxWYdGUVzLFFdBAaJlEFsVOVqOzkwS7lLhM6rXXssP6qvps+87XlVUi4MY9cByz6DKdairLezaBjTVxZ4cDd8=
script:
- npm --prefix client run build
deploy:
  on:
    branch: production
  provider: script
  script: npm --prefix client run deploy -- -r https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  skip_cleanup: true
